spring.application.name=ApiGateway
server.port=9191
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


spring.cloud.gateway.server.webmvc.routes[0].id=emplayee-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://emplayee-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/employees/** 

spring.cloud.gateway.server.webmvc.routes[1].id=department-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://department-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/department/** 

# Enable tracing and sample 100% of requests
management.tracing.export.enabled=true
management.tracing.sampling.probability=1.0

# Tell Spring Boot where your Zipkin server is running
management.tracing.export.zipkin.endpoint=http://localhost:9492/api/v2/spans

management.endpoints.web.exposure.include=*
