spring.application.name=ApiGateway
server.port=9191
eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka 

spring.cloud.gateway.server.webmvc.routes[0].id=emplayee-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://emplayee-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/employees/** 

spring.cloud.gateway.server.webmvc.routes[1].id=department-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://department-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/department/** 
